### ISSUE TITLE
Snapchat downloads to iOS device, but doesn't open

### ISSUE THREAD

**Issue by Billabong24** [Defying/TweakPatcher#8]
Hi, I have been reading and following the advice of many on these GitHub issues since I have been running into the same problems. But, I have found one that I haven't figured out. I have been prompted to the downloading on my device, which it does. I can see the snapchat application on my iPhone 5 on 9.3.1. I have also trusted the developer and it still does't work. Is it because I am on a iPhone 5? Although I have the proper version, I'm not an expert. Can u help
Any response and help is appreciated. Thanks!

**Comment by Defying** [comment]
what do you mean by "doesn't open"? does it crash on start?

**Comment by Billabong24** [comment]
Yes, I tap on it yet it doesn't load, I have trusted and see no response

**Comment by Billabong24** [comment]
It did ask me to trust the developer which makes sense, I do that, but it doesn't open. It looks as if it is about to load and it reroutes to the home screen on my iPhone. My terminal also says that it is on my phone and ready for me to press enter

**Comment by Defying** [comment]
https://github.com/Defying/TweakPatcher/wiki/Troubleshooting

scroll down and try the solution listed under "Snapchat crashes on launch"

**Comment by Billabong24** [comment]
Yes. I get this. But does this mean that I should also restart the terminal and get a new product and development name? do I use the same info from the failed snapchat terminal or make a complete new one?

**Comment by Billabong24** [comment]
??? I tried what it said on the wiki and it wasn't helping

**Comment by Defying** [comment]
@Billabong24 find the crash log (Settings -> Privacy -> Diagnostics & Usage -> Diagnostic & Usage Data) and screenshot it

post it here

**Comment by Briannmm** [comment]
I have the same problem. I'll attach the crash log
[LatestCrash-Snapchat.ips.txt](https://github.com/Defying/TweakPatcher/files/211704/LatestCrash-Snapchat.ips.txt)

**Comment by Defying** [comment]
@Briannmm where did you get your Snapchat IPA from?

**Comment by pleasehelpme123** [comment]
i got my snapchat ipa from vshare, the jailbroken version

**Comment by Briannmm** [comment]
@Defying I also got it from vshare. I tried a couple of different ones but they both crash. If I sign and sideload the ipa without patching it works

Also I noticed that I get notifications from snapchat when I get a snap even though I can't open it

**Comment by Briannmm** [comment]
I narrowed it down to DocsDylibLoader.dylib (I think). If I comment out line 343:
`$OPTOOL install -c load -p "@executable_path/"DocsDylibLoader.dylib -t $APPDIR/$APP_BINARY >> $LOGFILE 2>&1`
it loads snapchat and I can open it without crashing but obviously the tweak doesn't work.

What can be causing this? How can this exact file work for others but not on my phone?

**Comment by Briannmm** [comment]
@Defying I managed to solve my problem! This is what I did if it helps anyone:
1. Download Xcode 6.4 from developer.apple.com
2. Copy iphoneos8.4.sdk from Xcode 6.4 to Xcode 7.3 (into /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/)
3. Download DocsDylibLoader source from Defying's GitHub repo
4. Change SDKVERSION in DocsDylibLoader/Makefile from 9.3 to 8.4
5. Download theos-jailed from BishopFox's repo, move it into the DocsDylibLoader directory and rename it to theos
6. modify line 23 in theos/bin/bootstrap.sh to CydiaSubstrate_LDFLAGS = -dynamiclib -install_name "@executable_path/cydiasubst"
7. Make DocsDylibLoader
8. Replace the DocsDylibLoader.dylib file in TweakPatcher/patch with the one from DocsDylibLoader/obj
9. Patch the new DocsDylibLoader.dylib file so that it knows the correct location of cydia substrate by running (while in the TweakPatcher/patch directory):
../bin/patcho 4065786563757461626c655f706174682f4379646961537562737472617465 4065786563757461626C655F706174682F6379646961737562737400000000 ./DocsDylibLoader.dylib
This replaces "@executable_path/CydiaSubstrate" with "@executable_path/cydiasubst"
10. Run TweakPatcher

I assume this worked for me because I'm on iOS 8.4.1, I don't know if it'll work for anyone else.

Thank you for all your work!

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
